# Brains Memory System - Service Level Indicators, Objectives, and Agreements
# Based on existing Prometheus metrics and system capabilities

service_name: "brains-memory-system"
version: "2.0.0"

# ===================================
# Service Level Indicators (SLIs)
# ===================================
service_level_indicators:
  availability:
    description: "Percentage of time the service is up and responding"
    metric: "up{job='brains-memory'}"
    calculation: "avg_over_time(up{job='brains-memory'}[30d])"
    
  memory_efficiency:
    description: "Percentage of memory lookups that return a solution"
    metric: "memory_lookup_hits_total / memory_lookup_requests_total"
    calculation: "(rate(memory_lookup_hits_total[30d]) / rate(memory_lookup_requests_total[30d])) * 100"
    
  response_latency:
    description: "95th percentile response time for memory operations"
    metric: "memory_file_load_duration_seconds"
    calculation: "histogram_quantile(0.95, rate(memory_file_load_duration_seconds_bucket[30d]))"
    
  error_rate:
    description: "Percentage of requests resulting in errors"
    metric: "memory_lookup_misses_total / memory_lookup_requests_total"
    calculation: "(rate(memory_lookup_misses_total[30d]) / rate(memory_lookup_requests_total[30d])) * 100"
    
  conflict_resolution_efficiency:
    description: "Rate of successful conflict resolutions"
    metric: "memory_conflicts_resolved_total"
    calculation: "rate(memory_conflicts_resolved_total[30d])"

# ===================================
# Service Level Objectives (SLOs)
# ===================================
service_level_objectives:
  availability:
    target: 99.9
    unit: "percent"
    measurement_window: "30d"
    description: "Service must be available 99.9% of the time over 30 days"
    
  memory_efficiency:
    target: 90.0
    unit: "percent"
    measurement_window: "30d"
    description: "Memory lookup success rate must be ≥90% over 30 days"
    
  response_latency:
    target: 10.0
    unit: "milliseconds"
    measurement_window: "30d"
    description: "95th percentile response time must be ≤10ms over 30 days"
    
  error_rate:
    target: 1.0
    unit: "percent"
    measurement_window: "30d"
    description: "Error rate must be ≤1% over 30 days"
    
  conflict_resolution_efficiency:
    target: 0.5
    unit: "conflicts_per_second"
    measurement_window: "30d"
    description: "System must handle conflict resolution efficiently"

# ===================================
# Service Level Agreements (SLAs)
# ===================================
service_level_agreements:
  internal_sla:
    availability:
      commitment: 99.5
      unit: "percent"
      measurement_window: "30d"
      consequences: "Internal escalation to engineering team"
      
    memory_efficiency:
      commitment: 85.0
      unit: "percent"
      measurement_window: "30d"
      consequences: "Performance optimization sprint"
      
    response_latency:
      commitment: 50.0
      unit: "milliseconds"
      measurement_window: "30d"
      consequences: "Architecture review and optimization"
      
  external_sla:
    availability:
      commitment: 99.0
      unit: "percent"
      measurement_window: "30d"
      consequences: "Service credits or compensation as per contract"
      
    memory_efficiency:
      commitment: 80.0
      unit: "percent"
      measurement_window: "30d"
      consequences: "Service credits and improvement plan"

# ===================================
# Alert Thresholds
# ===================================
alert_thresholds:
  # Warning alerts - approaching SLO violation
  warning:
    availability: 99.95  # Warn when approaching 99.9% SLO
    memory_efficiency: 92.0  # Warn when approaching 90% SLO
    response_latency: 8.0  # Warn when approaching 10ms SLO
    error_rate: 0.8  # Warn when approaching 1% SLO
    
  # Critical alerts - SLO violation imminent
  critical:
    availability: 99.9  # Critical when at SLO threshold
    memory_efficiency: 90.0  # Critical when at SLO threshold
    response_latency: 10.0  # Critical when at SLO threshold
    error_rate: 1.0  # Critical when at SLO threshold
    
  # Emergency alerts - SLA violation risk
  emergency:
    availability: 99.5  # Emergency when approaching SLA
    memory_efficiency: 85.0  # Emergency when approaching SLA
    response_latency: 50.0  # Emergency when approaching SLA
    error_rate: 5.0  # Emergency when system severely degraded

# ===================================
# Error Budget
# ===================================
error_budget:
  availability:
    monthly_budget: 0.1  # 0.1% = 43.2 minutes downtime per month
    burn_rate_alerts:
      fast_burn: 14.4  # Alert if burning 2 weeks budget in 1 hour
      slow_burn: 1.0   # Alert if burning 30 days budget in 30 days
      
  memory_efficiency:
    monthly_budget: 10.0  # 10% miss rate budget
    burn_rate_alerts:
      fast_burn: 20.0  # Alert if exceeding budget quickly
      slow_burn: 12.0  # Alert if consistently near budget

# ===================================
# Reporting
# ===================================
reporting:
  frequency: "weekly"
  stakeholders:
    - "engineering-team"
    - "product-management"
    - "operations"
  
  metrics_included:
    - availability
    - memory_efficiency
    - response_latency
    - error_rate
    - conflict_resolution_efficiency
    
  dashboard_links:
    primary: "http://localhost:3000/d/brains-memory-dashboard"
    detailed: "http://localhost:9090/graph"
    tracing: "http://localhost:16686"